# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
    - job: Build
      displayName: Build job
      pool:
        vmImage: 'ubuntu-latest'
      steps:

      - task: Docker@2
        inputs:
          containerRegistry: 'ACR-GLOBAL-SERVICE-CONNECTION'
          repository: 'azure-devops-aks-acr'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
      
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)/kube-manifests'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          OverWrite: true
      
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'kube-manifest-artifacts'
          publishLocation: 'Container'